version: '3.9'

services:
  balance:
    build: .
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: balance_db
      REDIS_HOST: cache
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cache
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: balance_db
  cache:
    image: redis
    restart: always