---

is_debug: true

listen:
  type: port
  port: 8080

database_conn:
  driver: postgres
  host: localhost
  port: 5432
  dbname: balance_db
  user: abduhalim
  password: pass
  sslmode: disable

cache_conn:
  host: localhost
  port: 6379
  #password: pass

broker_conn:
  url: nats://localhost:4222

jwt_config:
  access_secret: secret
  refresh_secret: secret